// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALl2ZWbun62SOwTxJjd42jhDhiIWLVaps',
    appId: '1:48936538757:web:e17d1b5fa781517494cfec',
    messagingSenderId: '48936538757',
    projectId: 'mstf-example',
    authDomain: 'mstf-example.firebaseapp.com',
    storageBucket: 'mstf-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUZgL8FSDHQosU6yMMN5k9kMJBiYS_uK0',
    appId: '1:48936538757:android:ec49eb90194e9ffc94cfec',
    messagingSenderId: '48936538757',
    projectId: 'mstf-example',
    storageBucket: 'mstf-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmMoxXpUkn1Pg41CKFulZmIf7gvMMWIe0',
    appId: '1:48936538757:ios:5a7e240f8efefad794cfec',
    messagingSenderId: '48936538757',
    projectId: 'mstf-example',
    storageBucket: 'mstf-example.appspot.com',
    iosBundleId: 'com.example.authMstf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmMoxXpUkn1Pg41CKFulZmIf7gvMMWIe0',
    appId: '1:48936538757:ios:0742251aea6ab71794cfec',
    messagingSenderId: '48936538757',
    projectId: 'mstf-example',
    storageBucket: 'mstf-example.appspot.com',
    iosBundleId: 'com.example.authMstf.RunnerTests',
  );
}
